Obj:pickを追加
aiscript-dev/aiscript-dev.github.io pull request #14
Opened 2024-12-25 10:12 UTC by FineArchs

https://github.com/aiscript-dev/aiscript/pull/881 で追加された`Obj:pick`の項目を追加します。

2024-12-26 05:01 UTC, takejohn requested changes

2024-12-26 06:23 UTC, takejohn approved these changes

2024-12-26 11:47 UTC, kakkokari-gtyih commented
`pnpm i` を実行すべきかもしれない（PlaygroundのAiScriptバージョンを上げるため）

2024-12-26 14:21 UTC, takejohn commented
`pnpm i`だと何も起こらないので`pnpm up`ですかね

2024-12-28 09:16 UTC, FineArchs commented
`pnpm up`の実行をしました。

2024-12-28 09:23 UTC, takejohn approved these changes

2024-12-28 09:36 UTC, kakkokari-gtyih approved these changes

2024-12-29 21:44 UTC, merged